name: CI/CD to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    # Yeh job tabhi chalegi jab upar wali build-and-push successful ho jayegi
    needs: build-and-push
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Agar pehle se koi container chal raha hai toh use remove karo
            docker rm -f my-running-app || true
            
            # 2. Docker Hub se bilkul naya image pull karo
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
            
            # 3. Naya container port 8080 par chala do
            docker run -d -p 80:8080 --name my-running-app ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
